
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
images:
  hawk: 
    image: immnan/hawk
    pullPolicy: IfNotPresent
    tag: "0.5.2"
  apiserver: 
    image: immnan/hawk-apiserver
    pullPolicy: IfNotPresent
    tag: "0.2.0"
  ui: 
    image: immnan/hawk-ui
    pullPolicy: IfNotPresent
    tag: "0.2.5"
  mongo: 
    image: mongo
    pullPolicy: IfNotPresent
    tag: "8.0"
# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  labels: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: "hawk-sa"

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: 
  hawk: {}
  mongo: {}
  apiServer: {}
  ui: {}

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
labels: 
  hawk: 
    app: hawk
    type: master
  apiserver: 
    app: hawk-apiserver
    managedby: hawk
  ui: 
    app: hawk-ui
    managedby: hawk    
  mongo: 
    app: mongo    



podSecurityContext:
  hawk: 
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
    fsGroupChangePolicy: OnRootMismatch
    
  apiserver: {}
  ui: {}
  mongo: {}

securityContext: 
  hawk: {}
  apiserver: {}
  ui: {}
  mongo: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  
# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: hawk-gateway
  #  sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - hawk.k8s.net
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers

resources: 
  hawk: 
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "500m" 
  apiserver: {}
  ui: {}
  mongo: {}
# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
probes: 
  hawk:
    livenessProbe:
      httpGet:
        path: /health/live
        port: health
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health/ready
        port: health
      initialDelaySeconds: 60
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 2  
  apiserver: 
    livenessProbe:
      httpGet:
        path: /health/live
        port: 3000
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 2
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health/ready
        port: 3000
      initialDelaySeconds: 60
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3   
  ui: {}
  mongo: 
    livenessProbe:
      exec:
        command:
        - mongosh
        - --port
        - "27017"
        - --eval
        - "db.adminCommand('ping')"
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      exec:
        command:
        - mongosh
        - --port
        - "27017"
        - --eval
        - "db.adminCommand({ hello: 1 }).isWritablePrimary || db.adminCommand({ hello: 1 }).secondary"
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  apiserver:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80
  ui: {}


# Additional volumeMounts on the output Deployment definition.
volumeMounts: 
  hawk:
    - name: hawk-config
      mountPath: /etc/hawk/
      readOnly: true
    - name: job-template
      mountPath: /etc/hawk/template/
      readOnly: true
    - name: hawk-volume       # If renamed - update the configmap
      mountPath: /opt/hawk-data/
    - name: git-token-secret  # If renamed - update the configmap
      mountPath: /etc/hawk/secrets/git-secret-token
      readOnly: true
  apiserver: {}
  ui: {}
  mongo: 
    - name: mongo-storage
      mountPath: /data/db
    - name: mongo-config
      mountPath: /etc/mongo/
      readOnly: true  

# Additional volumes on the output Deployment definition.
volumes:
  hawk:  
    - name: hawk-config
      configMap:
        name: hawk-config
    - name: job-template
      configMap: 
        name: job-template
    - name: hawk-volume
      persistentVolumeClaim:
        claimName: hawk-shared-pvc
    - name: git-token-secret
      secret:
        secretName: git-secret-token
        optional: true
  apiserver: {}
  ui: {}
  mongo: 
    - name: mongo-storage
      persistentVolumeClaim:
        claimName: mongo-pvc
    - name: mongo-config
      configMap:
        name: mongo-config   

nodeSelector: 
  hawk: {}
  apiserver: {}
  ui: {}

tolerations: 
  hawk: []
  apiserver: []
  ui: []

affinity: 
  hawk: {}
  apiserver: {}
  ui: {}


hawkConfig: 
  configName: configlist.yaml
  configMountPath: /etc/hawk/ 
  templateName: job-git.yaml
  templateMountPath: /etc/hawk/template/ 

apiServerConfig: {}

uiConfig: {}


services:

  mongo: 
    name: mongo-svc
    type: ClusterIP
    port: 27017
    targetPort: 27017

  apiserver: 
    name: apiserver-svc
    type: ClusterIP
    port: 3000
    targetPort: 3000

  ui: 
    name: ui-svc
    type: ClusterIP
    port: 5000
    targetPort: 5000
