apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  {{ with .Values.labels.apiserver }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Release.Name }}-apiserver
spec:
  replicas: 1
  selector:
  {{with .Values.labels.apiserver }}  
    matchLabels:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  strategy: {}
  template:
    metadata:
  {{with .Values.labels.apiserver }}    
      labels:
      {{- toYaml . | nindent 8 }}
  {{- end }}
    spec:
      containers:
      - image: "{{ .Values.images.apiserver.repository }}:{{ .Values.images.apiserver.tag }}"
        imagePullPolicy: {{ .Values.images.apiserver.pullPolicy }}
        name: hawk-apiserver-ctr
        ports:
        - containerPort: {{ .Values.services.apiserver.targetPort }}
        env:  
        - name: CRED_FILE_PATH
          value: "/etc/hawk-apiserver/secret.txt"
        {{- with .Values.probes.apiserver }}  
        livenessProbe:
          {{- toYaml .livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .readinessProbe | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/hawk-apiserver/
          readOnly: true
      volumes:
      - name: secret-volume
        secret: 
          secretName: hawk-api-secret