apiVersion: v1
kind: ConfigMap
metadata:
  name: hawk-config
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.hawkConfig.configName }}: |-
{{- .Files.Get (printf "files/%s" .Values.hawkConfig.configName) | nindent 4 }}
                      

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: job-template
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.hawkConfig.templateName }}: |-
{{- .Files.Get (printf "files/%s" .Values.hawkConfig.templateName) | nindent 4 }}