{{- if .Values.autoscaling.orca.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-orca-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    tag: {{ .Chart.Version }}-{{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-orca
  minReplicas: {{ .Values.autoscaling.orca.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.orca.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.orca.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.orca.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.orca.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.orca.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
