apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.services.mongo.name }}
spec:
  clusterIP: None
  ports:
  - name: port-{{ .Values.services.mongo.name }}
    port: {{ .Values.services.mongo.port }}
    protocol: TCP
    targetPort: {{ .Values.services.mongo.targetPort }}
  selector:
    app: mongo
  type: {{ .Values.services.mongo.type }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.services.apiserver.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.services.apiserver.type }}
  selector:
  {{with .Values.labels.apiserver }}    
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  ports:
  - port: {{ .Values.services.apiserver.port }}
    targetPort: {{ .Values.services.apiserver.targetPort }}
    protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.services.ui.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.services.ui.type }}
  selector:
  {{with .Values.labels.ui }}    
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  ports:
  - port: {{ .Values.services.ui.port }}
    targetPort: {{ .Values.services.ui.targetPort }}
    protocol: TCP

