## QTE EMBEDDING SERVICES
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.services.embedding.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    {{- toYaml .Values.services.embedding.ports | nindent 4 }}
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    {{- toYaml .Values.labels.embedding | nindent 4 }}
    tag: {{ .Chart.Version }}-{{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.services.embedding.type }}
---
#vLLM service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.services.vllm.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    {{- toYaml .Values.services.vllm.ports | nindent 4 }}
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    {{- toYaml .Values.labels.vllm | nindent 4 }}
    tag: {{ .Chart.Version }}-{{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.services.vllm.type }}

---
#vLLM service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.services.orca.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    {{- toYaml .Values.services.orca.ports | nindent 4 }}
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    {{- toYaml .Values.labels.orca | nindent 4 }}
    tag: {{ .Chart.Version }}-{{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.services.orca.type }}