apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-svc
  name: mongo-svc
spec:
  clusterIP: None
  ports:
  - name: port-27017
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: hawk-apiserver-svc
  namespace: hawk 
spec:
  type: ClusterIP
  selector:
    app: hawk-apiserver
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: hawk-ui-svc
  namespace: hawk
spec:
  type: ClusterIP
  selector:
    app: hawk-ui-server
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

