apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orca-prod
spec:
  destination:
    namespace: hawk
    server: ''
  source:
    path: .
    repoURL: https://github.com/ImMnan/helm-rag_vLLM.git
    targetRevision: HEAD
    helm:
      releaseName: prod
      valueFiles:
        - Argo/orca-production-values.yaml
  sources: []
  project: default