apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: orca-infer-gateway
  namespace: hawk
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: orca-infer.ai
    - name: grpc
      protocol: HTTP
      port: 6334
      hostname: orca-infer.ai
    - name: https
      protocol: HTTPS
      port: 443
      hostname: orca-infer.ai
      tls:
        mode: Terminate
        certificateRefs:
          - name: orca-infer-tls
            kind: Secret
